### ISSUE TITLE
Sometimes button size goes negative

### ISSUE THREAD

**Issue by XertroV** [nbeerten/tm-refresh-leaderboard#3]
Sometimes the button size setting bugs out for me and I get like `-0.04` for both x and y size. Not sure why. Automatic placement off.

Using the version from plugin manager.

**Comment by nbeerten** [comment]
Sizes are calculated using this: `Screenheight / 22.5`, same for width. And `-1 / 22.5` is `-0.0444444...`... that seems to be the issue

**Comment by nbeerten** [comment]
Feel free to reopen if the issue still happens... But this should at least fix it in a way

**Comment by nbeerten** [comment]
Did another attempt at trying to fix it, this time with better logic: b30b5803c284e3bedb50217add1b8aaf2fe4fe70
