### ISSUE TITLE
divide by zero exception (zero height?)

### ISSUE THREAD

**Issue by XertroV** [nbeerten/tm-refresh-leaderboard#4]
was testing some stretched screen stuff with map info: https://github.com/sylae/tm-map-info/issues/3

The game is in fullscreen (not boarderless) and I get this when alt tabbing:

https://github.com/nbeerten/tm-refresh-leaderboard/blob/b30b5803c284e3bedb50217add1b8aaf2fe4fe70/src/Main.as#L55

![image](https://user-images.githubusercontent.com/1046448/218346247-b641359f-7056-428f-b943-78e7129e6706.png)

**Comment by nbeerten** [comment]
Thanks!

**Comment by nbeerten** [comment]
Also fixed the thing in your comment now; Check's for `Draw::GetHeight()` and `Draw::GetWidth()` are done independently now.
