### ISSUE TITLE
hide when leaderboard is hidden/game menu is open

### ISSUE THREAD

**Issue by ezio416** [nbeerten/tm-refresh-leaderboard#8]
By this, I mean when the settings, choose opponents, post-finish etc. in-game screens are displayed. Ideally I'd like it to mirror MapInfo which checks more things like pause menu open and UISequence, and I will probably work on a PR for it

<img width="361" alt="Screenshot 2024-01-05 120713" src="https://github.com/nbeerten/tm-refresh-leaderboard/assets/37951898/85cb3b38-c2bc-43e0-b73e-37a68852a6b9">

<img width="1034" alt="Screenshot 2024-01-05 120737" src="https://github.com/nbeerten/tm-refresh-leaderboard/assets/37951898/2cdf171b-cf76-4108-883e-547c3ee5b339">

**Comment by nbeerten** [comment]
I basically quit TM, so I don't think I'll make this myself, but if you could make a PR for it I can definitely get it merged

**Comment by ezio416** [comment]
Sorry to hear that! I'm happy to run the plugin unsigned indefinitely, so no rush in getting a new version pushed to the site, but I'm sure others may appreciate it

**Comment by nbeerten** [comment]
I'll merge the PR later today, thanks!
